title: Florijan HenÄel # your name (or website title) here
logo: "/images/PixBottle1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

 
<b> Programming skills </b>
  <br><br>
  - C#
   <br><br>
  - C++
   <br><br>
  - HTML
   <br><br>
  - Arduino
   <br><br>
   - Plc
   
 <b> Database </b>
  <br><br>
  - Firebase
  
  <b> Game Engines </b>
  <br><br>
  - Unity
  
  <b> 3D Modelling and animations </b>
  <br><br>
  - Blender
  <br><br>
  - Sweet Home 3D
  <br><br>
  - Mixamo
  <br><br>
  - Fuse
  <br><br>
  - MakeHuman
  
  
 <b> Digital art </b>
  <br><br>
  - Photoshop
  <br><br>
  - Adobe After effects
  
  <b> Other </b>
    <br><br>
    - Github


  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
